# Generated by Django 6.0.7 on 2026-08-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Comma separated skills', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ai_recommendation',
            field=models.TextField(blank=True, help_text='AI generated recommendation', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='experience_match_score',
            field=models.IntegerField(blank=True, help_text='Experience match percentage', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='experience_years',
            field=models.IntegerField(blank=True, help_text='Total years of experience', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='match_score',
            field=models.IntegerField(blank=True, help_text='Overall match percentage', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='parsed_education',
            field=models.TextField(blank=True, help_text='Extracted education details', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='parsed_experience',
            field=models.TextField(blank=True, help_text='Extracted experience details', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='parsed_skills',
            field=models.TextField(blank=True, help_text='Extracted skills from resume', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='skill_match_score',
            field=models.IntegerField(blank=True, help_text='Skills match percentage', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
